projects:
  database:
    schemaPath: src/prisma/generated/datamodel.graphql
    extensions:
      endpoints:
        default: http://localhost:4466
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/prisma/generated/prisma.binding.ts